table GOLD_LAYER_REJECT_CODES
	lineageTag: 5592976f-52ef-41bb-b2d7-02fdf110c3e8

	column REJECT_DESCRIPTION
		dataType: string
		lineageTag: 7cd1f8a6-0a89-4517-809a-146e4e774111
		summarizeBy: none
		sourceColumn: REJECT_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column LOAD_TS
		dataType: dateTime
		formatString: General Date
		lineageTag: 9548b5e7-81f8-4d9c-b76b-cfffe0abfb32
		summarizeBy: none
		sourceColumn: LOAD_TS

		annotation SummarizationSetBy = Automatic

	column VALID_REJECTED_CODE
		dataType: string
		lineageTag: 9c51b284-c717-45ae-959c-b0373de19f2d
		summarizeBy: none
		sourceColumn: VALID_REJECTED_CODE

		annotation SummarizationSetBy = Automatic

	column REJECT_CODE
		dataType: string
		lineageTag: 2d87c786-cb10-41f9-b253-59002c77a26d
		summarizeBy: none
		sourceColumn: REJECT_CODE

		annotation SummarizationSetBy = Automatic

	partition GOLD_LAYER_REJECT_CODES = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("PMG-PATIENTLENS_EXTENDED.snowflakecomputing.com","PRECISION_ADVISORS_WH",[Implementation="2.0"]),
				    RAW_NESTLE_Database = Source{[Name="RAW_NESTLE",Kind="Database"]}[Data],
				    SYMPHONY_ZENPEP_Schema = RAW_NESTLE_Database{[Name="SYMPHONY_ZENPEP",Kind="Schema"]}[Data],
				    GOLD_LAYER_REJECT_CODES_Table = SYMPHONY_ZENPEP_Schema{[Name="GOLD_LAYER_REJECT_CODES",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(GOLD_LAYER_REJECT_CODES_Table, "VALID_REJECTED_CODE", each if [REJECT_CODE] = Text.Select([REJECT_CODE], {"A".."Z","a".."z","0".."9"})
				then [REJECT_CODE]
				else null),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([VALID_REJECTED_CODE] <> null)),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each not Text.StartsWith([REJECT_CODE], "0")),
				    #"Filtered Rows2" = Table.SelectRows(#"Filtered Rows1", each true),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows2", {"REJECT_CODE"}),
				    #"Filtered Rows3" = Table.SelectRows(#"Removed Duplicates", each ([REJECT_CODE] = "2N" or [REJECT_CODE] = "76N" or [REJECT_CODE] = "8N" or [REJECT_CODE] = "AN" or [REJECT_CODE] = "ANU" or [REJECT_CODE] = "DN" or [REJECT_CODE] = "GN" or [REJECT_CODE] = "GNA" or [REJECT_CODE] = "HN" or [REJECT_CODE] = "IAN" or [REJECT_CODE] = "IN" or [REJECT_CODE] = "ING" or [REJECT_CODE] = "JN" or [REJECT_CODE] = "JYN" or [REJECT_CODE] = "KEN" or [REJECT_CODE] = "KN" or [REJECT_CODE] = "LIN" or [REJECT_CODE] = "MAN" or [REJECT_CODE] = "N0" or [REJECT_CODE] = "N13" or [REJECT_CODE] = "N29" or [REJECT_CODE] = "N39" or [REJECT_CODE] = "N4" or [REJECT_CODE] = "N5" or [REJECT_CODE] = "N7" or [REJECT_CODE] = "NE" or [REJECT_CODE] = "NF" or [REJECT_CODE] = "NL" or [REJECT_CODE] = "NN" or [REJECT_CODE] = "NN3" or [REJECT_CODE] = "NN7" or [REJECT_CODE] = "NNN" or [REJECT_CODE] = "NOE" or [REJECT_CODE] = "NOT" or [REJECT_CODE] = "NPD" or [REJECT_CODE] = "NQ" or [REJECT_CODE] = "NQ4" or [REJECT_CODE] = "NS" or [REJECT_CODE] = "NT" or [REJECT_CODE] = "NX" or [REJECT_CODE] = "ON" or [REJECT_CODE] = "ONC" or [REJECT_CODE] = "REN" or [REJECT_CODE] = "RON" or [REJECT_CODE] = "UN" or [REJECT_CODE] = "XN" or [REJECT_CODE] = "YN" or [REJECT_CODE] = "YND" or [REJECT_CODE] = "ZN")),
				    #"Filtered Rows4" = Table.SelectRows(#"Filtered Rows3", each not Text.StartsWith([REJECT_CODE], "7N")),
				    #"Filtered Rows5" = Table.SelectRows(#"Filtered Rows4", each [REJECT_CODE] <> "n")
				in
				    #"Filtered Rows5"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

