table GOLD_LAYER_DRUG
	lineageTag: 18a5780e-5e4d-463f-b67d-d2d6d1cdbf74

	column DRUG_ID
		dataType: int64
		formatString: 0
		lineageTag: 1c6de3a7-a893-4456-822d-d14b1a1caa02
		summarizeBy: none
		sourceColumn: DRUG_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DRUG_NAME
		dataType: string
		lineageTag: 74fe29ac-89c5-4573-9058-dd15ded31c11
		summarizeBy: none
		sourceColumn: DRUG_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NDC11
		dataType: string
		lineageTag: a42e4ff9-2a1f-425b-993b-39fa8a690763
		summarizeBy: none
		sourceColumn: NDC11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DRUG_STRENGTH
		dataType: string
		lineageTag: f86f856a-a7c0-49eb-a6cb-5374e7b136d9
		summarizeBy: none
		sourceColumn: DRUG_STRENGTH

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PACKAGE_SIZE
		dataType: double
		lineageTag: 5dc9c824-7cd3-4a2d-809b-adde88e0ba06
		summarizeBy: none
		sourceColumn: PACKAGE_SIZE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NEW_DRUG_NAME
		dataType: string
		lineageTag: 582d32a8-7cc0-4f08-9072-672cbf1e38f1
		summarizeBy: none
		sourceColumn: NEW_DRUG_NAME

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DRUG_BRAND =
			
			SWITCH(
			    TRUE(),
			    CONTAINSSTRING(UPPER('GOLD_LAYER_DRUG'[DRUG_NAME]), "CREON"), "CREON",
			    CONTAINSSTRING(UPPER('GOLD_LAYER_DRUG'[DRUG_NAME]), "ZENPEP"), "ZENPEP",
			    "OTHER"
			)
		lineageTag: 7840fa14-38fb-4a97-8e39-28fbba246500
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition GOLD_LAYER_DRUG = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("PMG-PATIENTLENS_EXTENDED.snowflakecomputing.com","PRECISION_ADVISORS_WH",[Implementation="2.0"]),
				    RAW_NESTLE_Database = Source{[Name="RAW_NESTLE",Kind="Database"]}[Data],
				    SYMPHONY_ZENPEP_Schema = RAW_NESTLE_Database{[Name="SYMPHONY_ZENPEP",Kind="Schema"]}[Data],
				    GOLD_LAYER_DRUG_Table = SYMPHONY_ZENPEP_Schema{[Name="GOLD_LAYER_DRUG",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GOLD_LAYER_DRUG_Table,{{"DRUG_ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

