table GOLD_LAYER_FINAL_STATUS
	lineageTag: 6f1d2c4a-6bfe-4408-95f0-cbe81c28d50a

	column PATIENT_ID
		dataType: int64
		formatString: 0
		lineageTag: 37b5e0c1-e224-4a27-9409-2486b5c2a57b
		summarizeBy: count
		sourceColumn: PATIENT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DRUG_ID
		dataType: int64
		formatString: 0
		lineageTag: c07abdf1-4055-4c9e-9bdb-abc2d488d4b3
		summarizeBy: none
		sourceColumn: DRUG_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PLAN_ID
		dataType: int64
		formatString: 0
		lineageTag: c5934aee-7f1c-42bc-acb4-3d8b799c5bab
		summarizeBy: none
		sourceColumn: PLAN_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EVENT_N
		dataType: int64
		lineageTag: d22e7f0b-3a27-4ee4-bef4-a5922426dc08
		summarizeBy: none
		sourceColumn: EVENT_N

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FINAL_TX
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8fc2f83f-dd88-4bab-844d-14e193e48250
		summarizeBy: none
		sourceColumn: FINAL_TX

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EVENT_LENGTH
		dataType: int64
		lineageTag: 30a84343-27ff-4bdf-a5ea-a5ee44df669f
		summarizeBy: none
		sourceColumn: EVENT_LENGTH

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FINAL_CLAIM_ID
		dataType: string
		lineageTag: a1449f21-816c-4501-998a-515ee53cb0a1
		summarizeBy: none
		sourceColumn: FINAL_CLAIM_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DAY_0_STATUS
		dataType: string
		lineageTag: 34a5b0aa-3955-45d7-9dc0-abe4d8276874
		summarizeBy: none
		sourceColumn: DAY_0_STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FINAL_STATUS_NUM
		dataType: string
		lineageTag: 966d9c7a-5599-40e9-af18-2a721d3c8933
		summarizeBy: none
		sourceColumn: FINAL_STATUS_NUM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DAY_0_REJECT_CODE
		dataType: string
		lineageTag: 888be18b-ae81-4272-8507-719f29f44ee9
		summarizeBy: none
		sourceColumn: DAY_0_REJECT_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FINAL_REJECT_CODE
		dataType: string
		lineageTag: ce1c8569-eb3f-45a4-89a2-185c20ff5825
		summarizeBy: none
		sourceColumn: FINAL_REJECT_CODE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PRACTITIONER_ID
		dataType: int64
		formatString: 0
		lineageTag: a96791a0-d62f-46e2-b372-6bb43524d706
		summarizeBy: none
		sourceColumn: PRACTITIONER_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PHARMACY_ZIP3
		dataType: string
		lineageTag: 2b3fd239-fc2c-4f75-b691-d0322580850f
		summarizeBy: none
		sourceColumn: PHARMACY_ZIP3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RX_NUMBER
		dataType: string
		lineageTag: 6c2d8016-b79a-48fb-8b5b-9fa088da75a6
		summarizeBy: none
		sourceColumn: RX_NUMBER

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DAYS_SUPPLY
		dataType: int64
		lineageTag: ae0ec17b-12fd-4a06-bedc-e1bd0b7ed53e
		summarizeBy: sum
		sourceColumn: DAYS_SUPPLY

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUANTITY
		dataType: double
		lineageTag: de14670b-363d-4799-b57c-fa6ad9e0017b
		summarizeBy: sum
		sourceColumn: QUANTITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NEW_TO_PRODUCT
		dataType: int64
		lineageTag: 4561cf12-a4a9-4509-bf86-5cff303da9e9
		summarizeBy: none
		sourceColumn: NEW_TO_PRODUCT

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PATIENT_PAY
		dataType: double
		lineageTag: 5cd89cd6-3fcb-4894-b1f0-228fdd12a766
		summarizeBy: sum
		sourceColumn: PATIENT_PAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PLAN_PAY
		dataType: double
		lineageTag: 98180d36-1952-4275-a2c5-3ea48b035788
		summarizeBy: sum
		sourceColumn: PLAN_PAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SECONDARY_PLAN_PAY
		dataType: double
		lineageTag: 11ca519d-ca96-4259-bf09-7159aa9f5aad
		summarizeBy: sum
		sourceColumn: SECONDARY_PLAN_PAY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PATIENT_OUT_OF_POCKET
		dataType: double
		lineageTag: f6551d9e-b9ee-4970-b2b4-9d336319cf43
		summarizeBy: sum
		sourceColumn: PATIENT_OUT_OF_POCKET

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COPAY_30
		dataType: double
		lineageTag: f8c252f9-23a1-4990-a9ab-714bc7f6dc3f
		summarizeBy: sum
		sourceColumn: COPAY_30

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RX_COUNT
		dataType: double
		formatString: 0.0
		lineageTag: f72bb90e-d966-469e-a0bf-ca08ae74d03e
		summarizeBy: sum
		sourceColumn: RX_COUNT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: 5fdd2504-fbca-4ed3-b2d3-1315646cf567
		summarizeBy: none
		sourceColumn: DATE_KEY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PATIENT_PAY Bin' =
			
			VAR Amount = GOLD_LAYER_FINAL_STATUS[PATIENT_PAY]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Amount), BLANK(),
			        Amount < 10, "$0 - $10",
			        Amount < 50, "$10 - $50",
			        Amount < 100, "$50 - $100",
			        Amount < 500, "$100 - $500",
			        "$500+"
			    )
		lineageTag: edf1dfc1-0040-4bbc-8824-e722d386326e
		summarizeBy: none
		sortByColumn: 'PATIENT_PAY Bin Sort'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PATIENT_OOP Bin' =
			
			VAR Amount = GOLD_LAYER_FINAL_STATUS[PATIENT_OUT_OF_POCKET]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Amount), BLANK(),
			        Amount < 10, "$0 - $10",
			        Amount < 50, "$10 - $50",
			        Amount < 100, "$50 - $100",
			        Amount < 500, "$100 - $500",
			        "$500+"
			    )
		lineageTag: d87bc1e6-44f3-42e4-86f2-aecfdad4e4a7
		summarizeBy: none
		sortByColumn: 'PATIENT_OOP Bin Sort'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PLAN_PAY Bin' =
			
			VAR Amount = GOLD_LAYER_FINAL_STATUS[PLAN_PAY]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Amount), BLANK(),
			        Amount < 1000, "$0 - $1K",
			        Amount < 2000, "$1K - $2K",
			        Amount < 3000, "$2K - $3K",
			        Amount < 4000, "$3K - $4K",
			        Amount < 5000, "$4K - $5K",
			        "$5K+"
			    )
		lineageTag: 33df6d3e-029c-48fb-b642-29365e7c3ba5
		summarizeBy: none
		sortByColumn: 'PLAN_PAY Bin Sort'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PATIENT_PAY Bin Sort' =
			
			VAR Amount = GOLD_LAYER_FINAL_STATUS[PATIENT_PAY]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Amount), BLANK(),
			        Amount < 10, 1,
			        Amount < 50, 2,
			        Amount < 100, 3,
			        Amount < 500, 4,
			        5
			    )
		formatString: 0
		lineageTag: e016c3f6-3aca-4be1-826e-51970c8d8f33
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PLAN_PAY Bin Sort' =
			
			VAR Amount = GOLD_LAYER_FINAL_STATUS[PLAN_PAY]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Amount), BLANK(),
			        Amount < 1000, 1,
			        Amount < 2000, 2,
			        Amount < 3000, 3,
			        Amount < 4000, 4,
			        Amount < 5000, 5,
			        6
			    )
		formatString: 0
		lineageTag: 49661a01-78a4-48f2-bcff-ea015717dae1
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'PATIENT_OOP Bin Sort' =
			
			VAR Amount = GOLD_LAYER_FINAL_STATUS[PATIENT_OUT_OF_POCKET]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(Amount), BLANK(),
			        Amount < 10, 1,
			        Amount < 50, 2,
			        Amount < 100, 3,
			        Amount < 500, 4,
			        5
			    )
		formatString: 0
		lineageTag: 4dc371ba-f1b0-463e-afb8-c57a708b5546
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Year = YEAR(GOLD_LAYER_FINAL_STATUS[FINAL_TX])
		formatString: 0
		lineageTag: cae4081a-48cf-4e98-be74-1b91febf246a
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Patient Year Key' = GOLD_LAYER_FINAL_STATUS[PATIENT_ID] * 10000 + GOLD_LAYER_FINAL_STATUS[Year]
		formatString: 0
		lineageTag: 6e13490d-ae8a-4dd6-900c-8481509e614a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition GOLD_LAYER_FINAL_STATUS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("PMG-PATIENTLENS_EXTENDED.snowflakecomputing.com","PRECISION_ADVISORS_WH",[Implementation="2.0"]),
				    RAW_NESTLE_Database = Source{[Name="RAW_NESTLE",Kind="Database"]}[Data],
				    SYMPHONY_ZENPEP_Schema = RAW_NESTLE_Database{[Name="SYMPHONY_ZENPEP",Kind="Schema"]}[Data],
				    GOLD_LAYER_FINAL_STATUS_Table = SYMPHONY_ZENPEP_Schema{[Name="GOLD_LAYER_FINAL_STATUS",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GOLD_LAYER_FINAL_STATUS_Table,{{"PATIENT_ID", Int64.Type}, {"DRUG_ID", Int64.Type}, {"PLAN_ID", Int64.Type}, {"DAY_0_CLAIM_ID", type text}, {"PRACTITIONER_ID", Int64.Type}, {"FINAL_TX", type date}, {"FINAL_CLAIM_ID", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"SECONDARY_PLAN_ID", "DAY_0_CLAIM_ID", "DAY_0_REJECTION_REASON_CODE", "DAY_0_REJECTION_REASON_DESCRIPTION", "FINAL_REJECTION_REASON_CODE", "FINAL_REJECTION_REASON_DESCRIPTION", "FINAL_STATUS"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "DATE_KEY", each Date.Year([FINAL_TX]) * 10000
				        + Date.Month([FINAL_TX]) * 100
				        + Date.Day([FINAL_TX])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"DATE_KEY", Int64.Type}})
				in
				    #"Changed Type1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

