table GOLD_LAYER_FINAL_STATUS
	lineageTag: 6f1d2c4a-6bfe-4408-95f0-cbe81c28d50a

	measure 'Count Of Claims' = count(GOLD_LAYER_FINAL_STATUS[FINAL_CLAIM_ID])
		formatString: 0
		lineageTag: 3dcfa60e-1f45-4db3-bb42-915c0d57887c

	column FINAL_CLAIM_ID
		dataType: string
		lineageTag: a1449f21-816c-4501-998a-515ee53cb0a1
		summarizeBy: none
		sourceColumn: FINAL_CLAIM_ID

		annotation SummarizationSetBy = Automatic

	column PATIENT_ID
		dataType: int64
		formatString: 0
		lineageTag: 37b5e0c1-e224-4a27-9409-2486b5c2a57b
		summarizeBy: count
		sourceColumn: PATIENT_ID

		annotation SummarizationSetBy = Automatic

	column DRUG_ID
		dataType: int64
		formatString: 0
		lineageTag: c07abdf1-4055-4c9e-9bdb-abc2d488d4b3
		summarizeBy: none
		sourceColumn: DRUG_ID

		annotation SummarizationSetBy = Automatic

	column PRACTITIONER_ID
		dataType: int64
		formatString: 0
		lineageTag: a96791a0-d62f-46e2-b372-6bb43524d706
		summarizeBy: none
		sourceColumn: PRACTITIONER_ID

		annotation SummarizationSetBy = Automatic

	column PLAN_ID
		dataType: int64
		formatString: 0
		lineageTag: c5934aee-7f1c-42bc-acb4-3d8b799c5bab
		summarizeBy: none
		sourceColumn: PLAN_ID

		annotation SummarizationSetBy = Automatic

	column EVENT_N
		dataType: int64
		lineageTag: d22e7f0b-3a27-4ee4-bef4-a5922426dc08
		summarizeBy: none
		sourceColumn: EVENT_N

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FINAL_TX
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8fc2f83f-dd88-4bab-844d-14e193e48250
		summarizeBy: none
		sourceColumn: FINAL_TX

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NEW_TO_PRODUCT
		dataType: int64
		lineageTag: 4561cf12-a4a9-4509-bf86-5cff303da9e9
		summarizeBy: none
		sourceColumn: NEW_TO_PRODUCT

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EVENT_LENGTH
		dataType: int64
		lineageTag: 30a84343-27ff-4bdf-a5ea-a5ee44df669f
		summarizeBy: none
		sourceColumn: EVENT_LENGTH

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DAY_0_STATUS
		dataType: string
		lineageTag: 34a5b0aa-3955-45d7-9dc0-abe4d8276874
		summarizeBy: none
		sourceColumn: DAY_0_STATUS

		annotation SummarizationSetBy = Automatic

	column FINAL_STATUS_NUM
		dataType: string
		lineageTag: 966d9c7a-5599-40e9-af18-2a721d3c8933
		summarizeBy: none
		sourceColumn: FINAL_STATUS_NUM

		annotation SummarizationSetBy = Automatic

	column FINAL_REJECT_CODE
		dataType: string
		lineageTag: ce1c8569-eb3f-45a4-89a2-185c20ff5825
		summarizeBy: none
		sourceColumn: FINAL_REJECT_CODE

		annotation SummarizationSetBy = Automatic

	column PHARMACY_ZIP3
		dataType: string
		lineageTag: 2b3fd239-fc2c-4f75-b691-d0322580850f
		summarizeBy: none
		sourceColumn: PHARMACY_ZIP3

		annotation SummarizationSetBy = Automatic

	column RX_NUMBER
		dataType: string
		lineageTag: 6c2d8016-b79a-48fb-8b5b-9fa088da75a6
		summarizeBy: none
		sourceColumn: RX_NUMBER

		annotation SummarizationSetBy = Automatic

	column DAYS_SUPPLY
		dataType: int64
		lineageTag: ae0ec17b-12fd-4a06-bedc-e1bd0b7ed53e
		summarizeBy: sum
		sourceColumn: DAYS_SUPPLY

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QUANTITY
		dataType: double
		lineageTag: de14670b-363d-4799-b57c-fa6ad9e0017b
		summarizeBy: sum
		sourceColumn: QUANTITY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PATIENT_PAY
		dataType: double
		lineageTag: 5cd89cd6-3fcb-4894-b1f0-228fdd12a766
		summarizeBy: sum
		sourceColumn: PATIENT_PAY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"GOLD_LAYER_FINAL_STATUS","TableItemName":"PATIENT_PAY (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column PLAN_PAY
		dataType: double
		lineageTag: 98180d36-1952-4275-a2c5-3ea48b035788
		summarizeBy: sum
		sourceColumn: PLAN_PAY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SECONDARY_PLAN_PAY
		dataType: double
		lineageTag: 11ca519d-ca96-4259-bf09-7159aa9f5aad
		summarizeBy: sum
		sourceColumn: SECONDARY_PLAN_PAY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PATIENT_OUT_OF_POCKET
		dataType: double
		lineageTag: f6551d9e-b9ee-4970-b2b4-9d336319cf43
		summarizeBy: sum
		sourceColumn: PATIENT_OUT_OF_POCKET

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"GOLD_LAYER_FINAL_STATUS","TableItemName":"PATIENT_OUT_OF_POCKET (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column COPAY_30
		dataType: double
		lineageTag: f8c252f9-23a1-4990-a9ab-714bc7f6dc3f
		summarizeBy: sum
		sourceColumn: COPAY_30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RX_COUNT
		dataType: double
		formatString: 0.0
		lineageTag: f72bb90e-d966-469e-a0bf-ca08ae74d03e
		summarizeBy: sum
		sourceColumn: RX_COUNT

		annotation SummarizationSetBy = Automatic

	column DAY_0_REJECT_CODE
		dataType: string
		lineageTag: 888be18b-ae81-4272-8507-719f29f44ee9
		summarizeBy: none
		sourceColumn: DAY_0_REJECT_CODE

		annotation SummarizationSetBy = Automatic

	column DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: 5fdd2504-fbca-4ed3-b2d3-1315646cf567
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = Automatic

	column 'PATIENT_PAY (bins)' =
			IF(
				ISBLANK('GOLD_LAYER_FINAL_STATUS'[PATIENT_PAY]),
				BLANK(),
				IF(
					'GOLD_LAYER_FINAL_STATUS'[PATIENT_PAY] >= 0,
					ROUNDDOWN('GOLD_LAYER_FINAL_STATUS'[PATIENT_PAY] / 2000, 0) * 2000,
					ROUNDUP('GOLD_LAYER_FINAL_STATUS'[PATIENT_PAY] / 2000, 0) * 2000
				)
			)
		lineageTag: 18037cc5-5205-4ad6-a383-1288e33b1d6e
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "GOLD_LAYER_FINAL_STATUS"
				          }
				        },
				        "Property": "PATIENT_PAY"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 2000.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"g","Entity":"GOLD_LAYER_FINAL_STATUS"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"PATIENT_PAY"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"PATIENT_PAY"}},"Size":2000.0}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PATIENT_PAY Bin Label' =
			
			VAR BinStart = GOLD_LAYER_FINAL_STATUS[PATIENT_PAY (bins)]
			VAR BinEnd = BinStart + 1000
			RETURN
			    FORMAT(BinStart / 1000, "0") & "K - " &
			    FORMAT(BinEnd / 1000, "0") & "K"
		lineageTag: edf1dfc1-0040-4bbc-8824-e722d386326e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'PATIENT_OUT_OF_POCKET (bins)' =
			IF(
				ISBLANK('GOLD_LAYER_FINAL_STATUS'[PATIENT_OUT_OF_POCKET]),
				BLANK(),
				IF(
					'GOLD_LAYER_FINAL_STATUS'[PATIENT_OUT_OF_POCKET] >= 0,
					ROUNDDOWN('GOLD_LAYER_FINAL_STATUS'[PATIENT_OUT_OF_POCKET] / 1000, 0) * 1000,
					ROUNDUP('GOLD_LAYER_FINAL_STATUS'[PATIENT_OUT_OF_POCKET] / 1000, 0) * 1000
				)
			)
		lineageTag: 57304ee2-ab8f-4a09-ac7d-726c1822106c
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "GOLD_LAYER_FINAL_STATUS"
				          }
				        },
				        "Property": "PATIENT_OUT_OF_POCKET"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 1000.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"g","Entity":"GOLD_LAYER_FINAL_STATUS"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"PATIENT_OUT_OF_POCKET"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"g"}},"Property":"PATIENT_OUT_OF_POCKET"}},"Size":1000.0}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition GOLD_LAYER_FINAL_STATUS = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("PMG-PATIENTLENS_EXTENDED.snowflakecomputing.com","PRECISION_ADVISORS_WH",[Implementation="2.0"]),
				    RAW_NESTLE_Database = Source{[Name="RAW_NESTLE",Kind="Database"]}[Data],
				    SYMPHONY_ZENPEP_Schema = RAW_NESTLE_Database{[Name="SYMPHONY_ZENPEP",Kind="Schema"]}[Data],
				    GOLD_LAYER_FINAL_STATUS_Table = SYMPHONY_ZENPEP_Schema{[Name="GOLD_LAYER_FINAL_STATUS",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GOLD_LAYER_FINAL_STATUS_Table,{{"PATIENT_ID", Int64.Type}, {"DRUG_ID", Int64.Type}, {"PLAN_ID", Int64.Type}, {"DAY_0_CLAIM_ID", type text}, {"PRACTITIONER_ID", Int64.Type}, {"FINAL_TX", type date}, {"FINAL_CLAIM_ID", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"SECONDARY_PLAN_ID", "DAY_0_CLAIM_ID", "DAY_0_REJECTION_REASON_CODE", "DAY_0_REJECTION_REASON_DESCRIPTION", "FINAL_REJECTION_REASON_CODE", "FINAL_REJECTION_REASON_DESCRIPTION", "FINAL_STATUS"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "DATE_KEY", each Date.Year([FINAL_TX]) * 10000
				        + Date.Month([FINAL_TX]) * 100
				        + Date.Day([FINAL_TX])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"DATE_KEY", Int64.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

