table GOLD_LAYER_PLAN
	lineageTag: 0cc2aefe-4be9-46e5-8ec7-c736ea2995f8

	column PLAN_ID
		dataType: int64
		formatString: 0
		lineageTag: b7c5d452-889f-4776-b3a1-03a7ab64fb56
		summarizeBy: none
		sourceColumn: PLAN_ID

		annotation SummarizationSetBy = Automatic

	column PLAN_NAME
		dataType: string
		lineageTag: 47449b27-9288-4cf7-b469-0aa2fcb9294e
		summarizeBy: none
		sourceColumn: PLAN_NAME

		annotation SummarizationSetBy = Automatic

	column PLAN_TYPE
		dataType: string
		lineageTag: 5f93e7cf-fa39-45d5-8449-41e9906433dd
		summarizeBy: none
		sourceColumn: PLAN_TYPE

		annotation SummarizationSetBy = Automatic

	column PLAN_TYPE_DESCRIPTION
		dataType: string
		lineageTag: 7298cfe7-65d2-4b73-b166-7243e5ecb811
		summarizeBy: none
		sourceColumn: PLAN_TYPE_DESCRIPTION

		annotation SummarizationSetBy = Automatic

	column PLAN_SUBTYPE
		dataType: string
		lineageTag: a1620e93-ea60-4443-8952-d7077d286709
		summarizeBy: none
		sourceColumn: PLAN_SUBTYPE

		annotation SummarizationSetBy = Automatic

	column PAYMENT_TYPE
		dataType: string
		lineageTag: 958ec96e-95c9-40bb-b21a-82ca05a13963
		summarizeBy: none
		sourceColumn: PAYMENT_TYPE

		annotation SummarizationSetBy = Automatic

	column NATIONAL_INSURER_NAME
		dataType: string
		lineageTag: aa60005c-d3f8-4f35-860f-3a07ad32d3ef
		summarizeBy: none
		sourceColumn: NATIONAL_INSURER_NAME

		annotation SummarizationSetBy = Automatic

	column NATIONAL_TYPE
		dataType: string
		lineageTag: 5f6f9d72-fb3d-4090-89fa-09fc9aab53df
		summarizeBy: none
		sourceColumn: NATIONAL_TYPE

		annotation SummarizationSetBy = Automatic

	column REGIONAL_NAME
		dataType: string
		lineageTag: 3694a1e1-a760-4d51-a2f4-7977c3230b5a
		summarizeBy: none
		sourceColumn: REGIONAL_NAME

		annotation SummarizationSetBy = Automatic

	column REGIONAL_TYPE
		dataType: string
		lineageTag: 180a7f5f-01a7-42e8-800f-2ac0396d9acf
		summarizeBy: none
		sourceColumn: REGIONAL_TYPE

		annotation SummarizationSetBy = Automatic

	column ORGANIZATION_NAME
		dataType: string
		lineageTag: b9b7f5e0-6db1-4d51-9304-49d7bfe763bf
		summarizeBy: none
		sourceColumn: ORGANIZATION_NAME

		annotation SummarizationSetBy = Automatic

	column ORGANIZATION_TYPE
		dataType: string
		lineageTag: 37a88a07-cf24-40da-88c8-ebf6572fcd11
		summarizeBy: none
		sourceColumn: ORGANIZATION_TYPE

		annotation SummarizationSetBy = Automatic

	column ADMIN_NAME
		dataType: string
		lineageTag: 44f926d7-b539-4d85-8521-844ceaf87f18
		summarizeBy: none
		sourceColumn: ADMIN_NAME

		annotation SummarizationSetBy = Automatic

	column ADMIN_TYPE
		dataType: string
		lineageTag: f7ee535b-42e3-4dfd-a34a-b94abb806ec7
		summarizeBy: none
		sourceColumn: ADMIN_TYPE

		annotation SummarizationSetBy = Automatic

	column LOAD_TS
		dataType: dateTime
		formatString: General Date
		lineageTag: 8382d5b0-45fe-46e6-8af2-455120936864
		summarizeBy: none
		sourceColumn: LOAD_TS

		annotation SummarizationSetBy = Automatic

	partition GOLD_LAYER_PLAN = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("PMG-PATIENTLENS_EXTENDED.snowflakecomputing.com","PRECISION_ADVISORS_WH",[Implementation="2.0"]),
				    RAW_NESTLE_Database = Source{[Name="RAW_NESTLE",Kind="Database"]}[Data],
				    SYMPHONY_ZENPEP_Schema = RAW_NESTLE_Database{[Name="SYMPHONY_ZENPEP",Kind="Schema"]}[Data],
				    GOLD_LAYER_PLAN_Table = SYMPHONY_ZENPEP_Schema{[Name="GOLD_LAYER_PLAN",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(GOLD_LAYER_PLAN_Table,{{"PLAN_ID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

