table Z2T_TARGET_LIST_Q2_2026
	lineageTag: 81d88b37-f7bb-4f04-acfb-57b1b167201a

	column ZIP
		dataType: string
		lineageTag: 66a255b8-37a2-40e9-8517-b97edbceb0d5
		dataCategory: PostalCode
		summarizeBy: none
		sourceColumn: ZIP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CITY
		dataType: string
		lineageTag: 93bc022b-8a9d-4999-b1eb-75675e592475
		dataCategory: City
		summarizeBy: none
		sourceColumn: CITY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STATE
		dataType: string
		lineageTag: 97ec1fd0-c78e-41e5-b3fd-742f596ca762
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: STATE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TERRITORY_ID
		dataType: string
		lineageTag: aee5b925-c9e2-45fd-942e-44befc9106cc
		summarizeBy: none
		sourceColumn: TERRITORY_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TERRITORY
		dataType: string
		lineageTag: 77b08d93-25be-4c55-ba1d-a771a580042e
		dataCategory: County
		summarizeBy: none
		sourceColumn: TERRITORY

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DISTRICT_ID
		dataType: string
		lineageTag: f673b611-134a-4395-80d3-cf0f2470a99d
		summarizeBy: none
		sourceColumn: DISTRICT_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DISTRICT
		dataType: string
		lineageTag: 2ee8e765-2976-45d7-a3c5-ab413bdb6387
		dataCategory: County
		summarizeBy: none
		sourceColumn: DISTRICT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REGION_ID
		dataType: string
		lineageTag: 39c29b82-df00-4016-b4e3-1d054dd9d7ae
		summarizeBy: none
		sourceColumn: REGION_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REGION
		dataType: string
		lineageTag: 39235762-b098-420f-9ec6-7ead37689fc8
		dataCategory: Country
		summarizeBy: none
		sourceColumn: REGION

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 765e64b1-f324-4167-82b2-c66db5f03dd4
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	hierarchy 'Country Hierarchy'
		lineageTag: 0ab46ae8-c34d-4732-a821-4d28a5b46bdd

		level Country
			lineageTag: a01a05a4-fb6c-42bf-834b-77917b6e3f5d
			column: Country

		level STATE
			lineageTag: 9bd1e101-d276-4903-9058-7f150ddb7f08
			column: STATE

		level TERRITORY
			lineageTag: ea4bfcfa-000c-4ae4-94af-b76d0bbf58d8
			column: TERRITORY

		level CITY
			lineageTag: a27db66a-b455-4c4d-87e8-a261c12c076d
			column: CITY

		level DISTRICT
			lineageTag: 49cbc921-7e3d-41c8-a5aa-171c4f657304
			column: DISTRICT

	partition Z2T_TARGET_LIST_Q2_2026 = m
		mode: import
		source =
				let
				    Source = Snowflake.Databases("PMG-PATIENTLENS_EXTENDED.snowflakecomputing.com","PRECISION_ADVISORS_WH",[Implementation="2.0"]),
				    RAW_NESTLE_Database = Source{[Name="RAW_NESTLE",Kind="Database"]}[Data],
				    MAPPING_Schema = RAW_NESTLE_Database{[Name="MAPPING",Kind="Schema"]}[Data],
				    Z2T_TARGET_LIST_Q2_2026_Table = MAPPING_Schema{[Name="Z2T_TARGET_LIST_Q2_2026",Kind="Table"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Z2T_TARGET_LIST_Q2_2026_Table, each [TERRITORY] <> "PUERTO RICO" and [TERRITORY] <> "WAKE ISLANDS" and [TERRITORY] <> "U.S. VIRGINIA ISLANDS"),
				    #"Inserted Literal" = Table.AddColumn(#"Filtered Rows", "Country", each "UNITED STATES", type text)
				in
				    #"Inserted Literal"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

